### PR TITLE
fix: Replace SDL controller calls with joystick ones in `Joystick`.

### LINKED ISSUE #632: Refuses to load the last used profiles (Windows 11 only)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Upon restarting the app, it loads with <new> profile shown and not the previous used ones for each joystick device

### Expected Behavior

I would expect "Load last used profile" to actually load the last used profiles upon restart

### Steps To Reproduce

Load app, set profiles up & save, close app, re-load app - profiles are not loaded

### Environment

```markdown
- OS:Windows 11 22H2
- AntiMicroX version:3.3.2
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nitz**
Closes #632

## Proposed changes 

This is enough of a fix to resolve the issue in #632, but there are a few other edge cases that investigation brought up that may cause a similar issue in the future.

`Joystick` was using calls to `SDK_GameController(*)` functions. On Windows 11 at least, the `SDK_Controller*` returned from `SDL_GameControllerOpen` in `Joystick`'s constructor was null, causing the unique ID building to be quite sparse. Thus, the Joystick's guid would match it's unique ID, causing profiles to fail to load automatically on startup. These changes resolve that, though some other oddities outlined in my comment in #632 do still persist.

### CODE REVIEW

File: src/joystick.cpp [hunk 1]
```diff
@@ -77,14 +77,16 @@ QString Joystick::getVendorString() const
 {
     QString temp = QString();
 
-    if (controller != nullptr)
+#if SDL_VERSION_ATLEAST(2, 0, 6)
```
Comment (pktiuk) [inline src/joystick.cpp:80]: Good that you removed it :)

Comment (pktiuk) [reply src/joystick.cpp:80]: https://github.com/AntiMicroX/antimicrox/blob/master/CMakeLists.txt#L22   
Here minimal SDL version is `2.0.6`

**Review by pktiuk — CHANGES_REQUESTED** [review]
Everything looks very good, only these version checks for SDL should be removed in my opinion.

File: src/joystick.cpp (hunk 1 above)
Comment (pktiuk) [reply src/joystick.cpp:80]: If there would such a need we could also bump it a little

**Comment by nitz** [comment]
Ah! I didn't catch the minimum version in cmakelists; perfect. I amended that commit to remove the 2.0.6 checks!

**Comment by pktiuk** [comment]
Thank you for your contribution and feel free to create new PR-s :)
